// Code generated by @apexlang/codegen. DO NOT EDIT.

package userinfo

import (
	"github.com/nanobus/nanobus/pkg/transport/filter"
)

type UserInfoV1Config struct {
	UserInfoURL string `json:"userInfoUrl" yaml:"userInfoUrl" msgpack:"userInfoUrl" mapstructure:"userInfoUrl" validate:"required"`
}

func UserInfoV1() (string, filter.Loader) {
	return "nanobus.filter.userinfo/v1", UserInfoV1Loader
}
