.PHONY: clean
clean:
	@rm -f $(CLEAN_FILES)

.PHONY: codegen
codegen: $(CODEGEN_FILES)
	@cargo +nightly fmt

.PHONY: doc
doc: ## Generate documentation
	@echo Unimplemented

##@ Helpers

.PHONY: help
help:  ## Display this help
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z0-9_\-.*]+:.*?##/ { printf "  \033[36m%-32s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)
