[package]
name = "wasmflow-traits"
version = "0.10.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/wasmflow/wasmflow-sdk"
description = "Rust library encapsulating the message packets sent across Wasmflow components."
documentation = "https://wasmflow.com"
keywords = ["wasmflow", "actor", "flow"]
categories = []
exclude = ["tests/*", ".github/*", ".gitignore"]
homepage = "https://wasmflow.com"


[features]

[dependencies]
wasmflow-packet = { path = "../wasmflow-packet", version = "0.10.0-beta.4" }
wasmflow-streams = { path = "../wasmflow-streams", version = "0.10.0-beta.4" }
serde = { version = "1" }
async-trait = "0.1"
tokio-stream = "0.1"
tokio = { version = "1", features = [] }

[dev-dependencies]
test-log = "0.2"
env_logger = "0.9"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
wasmflow-transport = { path = "../wasmflow-transport", version = "0.10.0-beta.4", features = [
  "async",
] }
