// Code generated by @apexlang/codegen. DO NOT EDIT.

package session

import (
	"github.com/nanobus/nanobus/pkg/handler"
	"github.com/nanobus/nanobus/pkg/transport/filter"
)

type SessionV1Config struct {
	Handler handler.Handler `json:"handler" yaml:"handler" msgpack:"handler" mapstructure:"handler" validate:"required"`
}

func SessionV1() (string, filter.Loader) {
	return "nanobus.filter.session/v1", SessionV1Loader
}
