codegen:
  cargo run --manifest-path ../codegen-bin/Cargo.toml -- tests/testdata/import-types.wick src/import_types

test:
  cargo test
  cargo run --manifest-path ../../crates/bins/wick/Cargo.toml -- test tests/testdata/import-types.wick --trace
