project_name := "{{project-name | snake_case}}"
build: setup
    cargo build --release --target=wasm32-unknown-unknown
    cp ./target/wasm32-unknown-unknown/release/*.wasm ./build/
    wick wasm sign ./build/{{project_name}}.wasm component.wick
debug: setup
    cargo +nightly build --target=wasm32-wasi
    cp ./target/wasm32-wasi/debug/*.wasm ./build/
    wick wasm sign ./build/{{project_name}}.wasm component.wick
setup:
    mkdir -p build
test: build
    wick test component.wick
clean:
  cargo clean
