build: setup
    cargo build --release --target=wasm32-unknown-unknown
    cp ./target/wasm32-unknown-unknown/release/*.wasm ./build/
    wick wasm sign ./build/{{project-name | snake_case}}.wasm component.yaml
debug: setup
    cargo +nightly build --target=wasm32-wasi
    cp ./target/wasm32-wasi/debug/*.wasm ./build/
    wick wasm sign ./build/{{project-name | snake_case}}.wasm component.yaml
setup:
    mkdir -p build
clean:
  cargo clean
