build: setup
    cargo build --release --target=wasm32-wasi
    cp ./target/wasm32-wasi/release/*.wasm ./build/
    cargo run --manifest-path ../../bins/wick/Cargo.toml -- wasm sign ./build/test_cli_with_db.wasm component.yaml
debug: setup
    cargo +nightly build --target=wasm32-wasi --features localgen
    cp ./target/wasm32-wasi/debug/*.wasm ./build/
    cargo run --manifest-path ../../bins/wick/Cargo.toml -- wasm sign ./build/test_cli_with_db.wasm component.yaml
setup:
    mkdir -p build
clean:
  cargo clean
  rm -rf build/*
