// Code generated by @apexlang/codegen. DO NOT EDIT.

package paseto

import (
	"github.com/nanobus/nanobus/pkg/transport/filter"
)

type PasetoV1Config struct {
	Audience       *string `json:"audience,omitempty" yaml:"audience,omitempty" msgpack:"audience,omitempty" mapstructure:"audience"`
	Issuer         *string `json:"issuer,omitempty" yaml:"issuer,omitempty" msgpack:"issuer,omitempty" mapstructure:"issuer"`
	V4PublicKey    []byte  `json:"v4PublicKey,omitempty" yaml:"v4PublicKey,omitempty" msgpack:"v4PublicKey,omitempty" mapstructure:"v4PublicKey"`
	V4PublicKeyHex *string `json:"v4PublicKeyHex,omitempty" yaml:"v4PublicKeyHex,omitempty" msgpack:"v4PublicKeyHex,omitempty" mapstructure:"v4PublicKeyHex"`
	V3PublicKey    []byte  `json:"v3PublicKey,omitempty" yaml:"v3PublicKey,omitempty" msgpack:"v3PublicKey,omitempty" mapstructure:"v3PublicKey"`
	V3PublicKeyHex *string `json:"v3PublicKeyHex,omitempty" yaml:"v3PublicKeyHex,omitempty" msgpack:"v3PublicKeyHex,omitempty" mapstructure:"v3PublicKeyHex"`
	V2PublicKey    []byte  `json:"v2PublicKey,omitempty" yaml:"v2PublicKey,omitempty" msgpack:"v2PublicKey,omitempty" mapstructure:"v2PublicKey"`
	V2PublicKeyHex *string `json:"v2PublicKeyHex,omitempty" yaml:"v2PublicKeyHex,omitempty" msgpack:"v2PublicKeyHex,omitempty" mapstructure:"v2PublicKeyHex"`
	V4LocalKey     []byte  `json:"v4LocalKey,omitempty" yaml:"v4LocalKey,omitempty" msgpack:"v4LocalKey,omitempty" mapstructure:"v4LocalKey"`
	V4LocalKeyHex  *string `json:"v4LocalKeyHex,omitempty" yaml:"v4LocalKeyHex,omitempty" msgpack:"v4LocalKeyHex,omitempty" mapstructure:"v4LocalKeyHex"`
	V3LocalKey     []byte  `json:"v3LocalKey,omitempty" yaml:"v3LocalKey,omitempty" msgpack:"v3LocalKey,omitempty" mapstructure:"v3LocalKey"`
	V3LocalKeyHex  *string `json:"v3LocalKeyHex,omitempty" yaml:"v3LocalKeyHex,omitempty" msgpack:"v3LocalKeyHex,omitempty" mapstructure:"v3LocalKeyHex"`
	V2LocalKey     []byte  `json:"v2LocalKey,omitempty" yaml:"v2LocalKey,omitempty" msgpack:"v2LocalKey,omitempty" mapstructure:"v2LocalKey"`
	V2LocalKeyHex  *string `json:"v2LocalKeyHex,omitempty" yaml:"v2LocalKeyHex,omitempty" msgpack:"v2LocalKeyHex,omitempty" mapstructure:"v2LocalKeyHex"`
}

func PasetoV1() (string, filter.Loader) {
	return "nanobus.filter.paseto/v1", PasetoV1Loader
}
