build: setup
    cargo build --release --target=wasm32-unknown-unknown
    cp ./target/wasm32-unknown-unknown/release/*.wasm ./build/
    cargo run --manifest-path ../../../Cargo.toml -- wasm sign ./build/test_http_trigger_component.wasm component.yaml
debug: setup
    cargo +nightly build --target=wasm32-wasi --features localgen
    cp ./target/wasm32-wasi/debug/*.wasm ./build/
    cargo run --manifest-path ../../../Cargo.toml -- wasm sign ./build/test_http_trigger_component.wasm component.yaml
setup:
    mkdir -p build
clean:
  cargo clean
  rm -rf build/*
