// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     spec.avsc
 */
package avro

import (
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
	"io"
)

func writeMapUnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleString(r map[string]*UnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleString, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for k, e := range r {
		err = vm.WriteString(k, w)
		if err != nil {
			return err
		}
		err = writeUnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleString(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type MapUnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleStringWrapper struct {
	Target *map[string]*UnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleString
	keys   []string
	values []*UnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleString
}

func (_ *MapUnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleStringWrapper) SetBoolean(v bool) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleStringWrapper) SetInt(v int32) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleStringWrapper) SetLong(v int64) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleStringWrapper) SetFloat(v float32) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleStringWrapper) SetDouble(v float64) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleStringWrapper) SetBytes(v []byte) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleStringWrapper) SetString(v string) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleStringWrapper) SetUnionElem(v int64) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleStringWrapper) Get(i int) types.Field {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleStringWrapper) SetDefault(i int) {
	panic("Unsupported operation")
}

func (r *MapUnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleStringWrapper) HintSize(s int) {
	if r.keys == nil {
		r.keys = make([]string, 0, s)
		r.values = make([]*UnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleString, 0, s)
	}
}

func (r *MapUnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleStringWrapper) NullField(_ int) {
	r.values[len(r.values)-1] = nil
}

func (r *MapUnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleStringWrapper) Finalize() {
	for i := range r.keys {
		(*r.Target)[r.keys[i]] = r.values[i]
	}
}

func (r *MapUnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleStringWrapper) AppendMap(key string) types.Field {
	r.keys = append(r.keys, key)
	var v *UnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleString
	v = NewUnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleString()

	r.values = append(r.values, v)
	return r.values[len(r.values)-1]
}

func (_ *MapUnionNullBoolMapCloudEventDataArrayCloudEventDataDoubleStringWrapper) AppendArray() types.Field {
	panic("Unsupported operation")
}
