// Code generated by @apexlang/codegen. DO NOT EDIT.

package http

import (
	"github.com/nanobus/nanobus/pkg/runtime"
	"github.com/nanobus/nanobus/pkg/transport"
)

// This component provides extensible HTTP server capabilities. The functionality
// of your application is added by including `routers` and `middleware` components.
type HttpServerV1Config struct {
	// The listening address of the server.
	Address string `json:"address" yaml:"address" msgpack:"address" mapstructure:"address" validate:"required"`
	// Array of [HTTP Middleware](/category/http-middleware) component configurations.
	Middleware []runtime.Component `json:"middleware,omitempty" yaml:"middleware,omitempty" msgpack:"middleware,omitempty" mapstructure:"middleware" validate:"dive"`
	// Array of [HTTP Router](/category/http-routers) component configurations.
	Routers []runtime.Component `json:"routers,omitempty" yaml:"routers,omitempty" msgpack:"routers,omitempty" mapstructure:"routers" validate:"dive"`
}

func HttpServerV1() (string, transport.Loader) {
	return "nanobus.transport.http.server/v1", HttpServerV1Loader
}
