// Code generated by NanoBus codegen utilities. DO NOT EDIT.

// deno-lint-ignore-file no-explicit-any no-unused-vars ban-unused-ignore
import {
  CodecRef,
  Component,
  DataExpr,
  Handler,
  Entity,
  ResourceRef,
  Step,
  ValueExpr
} from "../nanobus.ts";

export interface SendMessageConfig {
  resource?: ResourceRef;
  channelId: ValueExpr;
  content: ValueExpr;
}

export function SendMessage(
  config: SendMessageConfig
): Component<SendMessageConfig> {
  return {
    uses: "@discord/send_message",
    with: config
  };
}
