// Code generated by NanoBus codegen utilities. DO NOT EDIT.

// deno-lint-ignore-file no-explicit-any no-unused-vars ban-unused-ignore
import {
  CodecRef,
  Component,
  DataExpr,
  Handler,
  Entity,
  ResourceRef,
  Step,
  ValueExpr
} from "../nanobus.ts";

export type FilePath = string;

export type Duration = number;

export interface MigratePostgresV1Config {
  // The data source connection string.
  dataSource: string;
  // The directory to use for migration sources.
  directory?: string;
  // The directory to use for migration sources.
  sourceUrl?: string;
  migrationsTable?: string;
  migrationsTableQuoted?: boolean;
  multiStatementEnabled?: boolean;
  databaseName?: string;
  schemaName?: string;
  statementTimeout?: Duration;
  multiStatementMaxSize?: number;
}

export function MigratePostgresV1(
  config: MigratePostgresV1Config
): Component<MigratePostgresV1Config> {
  return {
    uses: "nanobus.migrate.postgres/v1",
    with: config
  };
}
