// Code generated by NanoBus codegen utilities. DO NOT EDIT.

// deno-lint-ignore-file no-explicit-any no-unused-vars ban-unused-ignore
import {
  CodecRef,
  Component,
  DataExpr,
  Handler,
  Entity,
  ResourceRef,
  Step,
  ValueExpr
} from "../nanobus.ts";

export type FilePath = string;

export interface MigrateMSSQLV1Config {
  dataSource: string;
  directory?: string;
  sourceUrl?: string;
  migrationsTable?: string;
  databaseName?: string;
  schemaName?: string;
}

export function MigrateMSSQLV1(
  config: MigrateMSSQLV1Config
): Component<MigrateMSSQLV1Config> {
  return {
    uses: "nanobus.migrate.mssql/v1",
    with: config
  };
}
