// Code generated by NanoBus codegen utilities. DO NOT EDIT.

// deno-lint-ignore-file no-explicit-any no-unused-vars ban-unused-ignore
import {
  Component,
  DataExpr,
  Handler,
  ResourceRef,
  Step,
  ValueExpr
} from "../nanobus.ts";

export type FilePath = string;

export interface MigratePostgresV1Config {
  // The data source connection string.
  dataSource: string;
  // The directory to use for migration sources.
  directory?: FilePath;
  // The directory to use for migration sources.
  sourceUrl?: string;
}

export function MigratePostgresV1(
  config: MigratePostgresV1Config
): Component<MigratePostgresV1Config> {
  return {
    uses: "nanobus.migrate.postgres/v1",
    with: config
  };
}
