// Code generated by NanoBus codegen utilities. DO NOT EDIT.

// deno-lint-ignore-file no-explicit-any no-unused-vars ban-unused-ignore
import {
  CodecRef,
  Component,
  DataExpr,
  Handler,
  Entity,
  ResourceRef,
  Step,
  ValueExpr
} from "../nanobus.ts";

export interface JWTV1Config {
  rsaPublicKeyFile?: string;
  rsaPublicKeyString?: string;
  ecdsaPublicKeyFile?: string;
  ecdsaPublicKeyString?: string;
  hmacSecretKeyFile?: string;
  hmacSecretKeyBase64?: boolean;
  hmacSecretKeyString?: string;
  jwksUrl?: string;
}

export function JWTV1(config: JWTV1Config): Component<JWTV1Config> {
  return {
    uses: "nanobus.filter.jwt/v1",
    with: config
  };
}
