// Code generated by NanoBus codegen utilities. DO NOT EDIT.

// deno-lint-ignore-file no-explicit-any no-unused-vars ban-unused-ignore
import {
  CodecRef,
  Component,
  DataExpr,
  Handler,
  Entity,
  ResourceRef,
  Step,
  ValueExpr
} from "../nanobus.ts";

export interface DaprServerV1Config {
  address?: string;
  subscriptions?: Subscription[];
  bindings?: Binding[];
}

export function DaprServerV1(
  config: DaprServerV1Config
): Component<DaprServerV1Config> {
  return {
    uses: "nanobus.transport.dapr/v1",
    with: config
  };
}

export interface Subscription {
  pubsub: string;
  topic: string;
  metadata?: { [key: string]: string };
  types?: { [key: string]: Handler };
  handler?: Handler;
  codec: CodecRef;
  disableTopicValidation?: boolean;
}

export interface Binding {
  name: string;
  handler: Handler;
  codec: CodecRef;
}
