// Code generated by NanoBus codegen utilities. DO NOT EDIT.

// deno-lint-ignore-file no-explicit-any no-unused-vars ban-unused-ignore
import {
  CodecRef,
  Component,
  DataExpr,
  Handler,
  ResourceRef,
  Step,
  ValueExpr
} from "../nanobus.ts";

export interface HttpServerV1Config {
  // The listening address of the server.
  address: string;
  // Array of [HTTP Middleware](/category/http-middleware) component configurations.
  middleware?: Component<any>[];
  // Array of [HTTP Router](/category/http-routers) component configurations.
  routers?: Component<any>[];
}

export function HttpServerV1(
  config: HttpServerV1Config
): Component<HttpServerV1Config> {
  return {
    uses: "nanobus.transport.http.server/v1",
    with: config
  };
}
