// Code generated by NanoBus codegen utilities. DO NOT EDIT.

// deno-lint-ignore-file no-explicit-any no-unused-vars ban-unused-ignore
import {
  CodecRef,
  Component,
  DataExpr,
  Handler,
  ResourceRef,
  Step,
  ValueExpr
} from "../nanobus.ts";

export interface PasetoV1Config {
  audience?: string;
  issuer?: string;
  v4PublicKey?: ArrayBuffer;
  v4PublicKeyHex?: string;
  v3PublicKey?: ArrayBuffer;
  v3PublicKeyHex?: string;
  v2PublicKey?: ArrayBuffer;
  v2PublicKeyHex?: string;
  v4LocalKey?: ArrayBuffer;
  v4LocalKeyHex?: string;
  v3LocalKey?: ArrayBuffer;
  v3LocalKeyHex?: string;
  v2LocalKey?: ArrayBuffer;
  v2LocalKeyHex?: string;
}

export function PasetoV1(config: PasetoV1Config): Component<PasetoV1Config> {
  return {
    uses: "nanobus.filter.paseto/v1",
    with: config
  };
}
