// Code generated by NanoBus codegen utilities. DO NOT EDIT.

// deno-lint-ignore-file no-explicit-any no-unused-vars ban-unused-ignore
import {
  CodecRef,
  Component,
  DataExpr,
  Handler,
  Entity,
  ResourceRef,
  Step,
  ValueExpr
} from "../nanobus.ts";

export interface SchedulerV1Config {
  schedules: Schedule[];
}

export function SchedulerV1(
  config: SchedulerV1Config
): Component<SchedulerV1Config> {
  return {
    uses: "nanobus.transport.time.scheduler/v1",
    with: config
  };
}

export interface Schedule {
  schedule: string;
  handler: Handler;
  repeat?: number;
}
