// Code generated by @apexlang/codegen. DO NOT EDIT.

package dapr

import (
	"github.com/nanobus/nanobus/pkg/handler"
	"github.com/nanobus/nanobus/pkg/transport"
)

type CodecRef string

type DaprServerV1Config struct {
	Address       string         `json:"address" yaml:"address" msgpack:"address" mapstructure:"address" validate:"required"`
	Subscriptions []Subscription `json:"subscriptions,omitempty" yaml:"subscriptions,omitempty" msgpack:"subscriptions,omitempty" mapstructure:"subscriptions" validate:"dive"`
	Bindings      []Binding      `json:"bindings,omitempty" yaml:"bindings,omitempty" msgpack:"bindings,omitempty" mapstructure:"bindings" validate:"dive"`
}

func DaprServerV1() (string, transport.Loader) {
	return "nanobus.transport.dapr/v1", DaprServerV1Loader
}

type Subscription struct {
	Pubsub                 string                     `json:"pubsub" yaml:"pubsub" msgpack:"pubsub" mapstructure:"pubsub" validate:"required"`
	Topic                  string                     `json:"topic" yaml:"topic" msgpack:"topic" mapstructure:"topic" validate:"required"`
	Metadata               map[string]string          `json:"metadata" yaml:"metadata" msgpack:"metadata" mapstructure:"metadata" validate:"dive"`
	Types                  map[string]handler.Handler `json:"types,omitempty" yaml:"types,omitempty" msgpack:"types,omitempty" mapstructure:"types" validate:"dive"`
	Handler                *handler.Handler           `json:"handler,omitempty" yaml:"handler,omitempty" msgpack:"handler,omitempty" mapstructure:"handler"`
	Codec                  CodecRef                   `json:"codec" yaml:"codec" msgpack:"codec" mapstructure:"codec"`
	DisableTopicValidation bool                       `json:"disableTopicValidation" yaml:"disableTopicValidation" msgpack:"disableTopicValidation" mapstructure:"disableTopicValidation"`
}

type Binding struct {
	Name    string          `json:"name" yaml:"name" msgpack:"name" mapstructure:"name" validate:"required"`
	Handler handler.Handler `json:"handler" yaml:"handler" msgpack:"handler" mapstructure:"handler" validate:"required"`
	Codec   CodecRef        `json:"codec" yaml:"codec" msgpack:"codec" mapstructure:"codec"`
}
