// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     spec.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

func writeArrayCloudEventData(r []CloudEventData, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for _, e := range r {
		err = writeCloudEventData(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type ArrayCloudEventDataWrapper struct {
	Target *[]CloudEventData
}

func (_ ArrayCloudEventDataWrapper) SetBoolean(v bool)                { panic("Unsupported operation") }
func (_ ArrayCloudEventDataWrapper) SetInt(v int32)                   { panic("Unsupported operation") }
func (_ ArrayCloudEventDataWrapper) SetLong(v int64)                  { panic("Unsupported operation") }
func (_ ArrayCloudEventDataWrapper) SetFloat(v float32)               { panic("Unsupported operation") }
func (_ ArrayCloudEventDataWrapper) SetDouble(v float64)              { panic("Unsupported operation") }
func (_ ArrayCloudEventDataWrapper) SetBytes(v []byte)                { panic("Unsupported operation") }
func (_ ArrayCloudEventDataWrapper) SetString(v string)               { panic("Unsupported operation") }
func (_ ArrayCloudEventDataWrapper) SetUnionElem(v int64)             { panic("Unsupported operation") }
func (_ ArrayCloudEventDataWrapper) Get(i int) types.Field            { panic("Unsupported operation") }
func (_ ArrayCloudEventDataWrapper) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ ArrayCloudEventDataWrapper) Finalize()                        {}
func (_ ArrayCloudEventDataWrapper) SetDefault(i int)                 { panic("Unsupported operation") }
func (r ArrayCloudEventDataWrapper) HintSize(s int) {
	if len(*r.Target) == 0 {
		*r.Target = make([]CloudEventData, 0, s)
	}
}
func (r ArrayCloudEventDataWrapper) NullField(i int) {
	panic("Unsupported operation")
}

func (r ArrayCloudEventDataWrapper) AppendArray() types.Field {
	var v CloudEventData
	v = NewCloudEventData()

	*r.Target = append(*r.Target, v)
	return &types.Record{Target: &(*r.Target)[len(*r.Target)-1]}
}
