// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     spec.avsc
 */
package avro

import (
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
	"io"
)

func writeMapUnionNullBoolCloudEventDataDoubleString(r map[string]*UnionNullBoolCloudEventDataDoubleString, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for k, e := range r {
		err = vm.WriteString(k, w)
		if err != nil {
			return err
		}
		err = writeUnionNullBoolCloudEventDataDoubleString(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type MapUnionNullBoolCloudEventDataDoubleStringWrapper struct {
	Target *map[string]*UnionNullBoolCloudEventDataDoubleString
	keys   []string
	values []*UnionNullBoolCloudEventDataDoubleString
}

func (_ *MapUnionNullBoolCloudEventDataDoubleStringWrapper) SetBoolean(v bool) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolCloudEventDataDoubleStringWrapper) SetInt(v int32) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolCloudEventDataDoubleStringWrapper) SetLong(v int64) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolCloudEventDataDoubleStringWrapper) SetFloat(v float32) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolCloudEventDataDoubleStringWrapper) SetDouble(v float64) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolCloudEventDataDoubleStringWrapper) SetBytes(v []byte) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolCloudEventDataDoubleStringWrapper) SetString(v string) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolCloudEventDataDoubleStringWrapper) SetUnionElem(v int64) {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolCloudEventDataDoubleStringWrapper) Get(i int) types.Field {
	panic("Unsupported operation")
}
func (_ *MapUnionNullBoolCloudEventDataDoubleStringWrapper) SetDefault(i int) {
	panic("Unsupported operation")
}

func (r *MapUnionNullBoolCloudEventDataDoubleStringWrapper) HintSize(s int) {
	if r.keys == nil {
		r.keys = make([]string, 0, s)
		r.values = make([]*UnionNullBoolCloudEventDataDoubleString, 0, s)
	}
}

func (r *MapUnionNullBoolCloudEventDataDoubleStringWrapper) NullField(_ int) {
	r.values[len(r.values)-1] = nil
}

func (r *MapUnionNullBoolCloudEventDataDoubleStringWrapper) Finalize() {
	for i := range r.keys {
		(*r.Target)[r.keys[i]] = r.values[i]
	}
}

func (r *MapUnionNullBoolCloudEventDataDoubleStringWrapper) AppendMap(key string) types.Field {
	r.keys = append(r.keys, key)
	var v *UnionNullBoolCloudEventDataDoubleString
	v = NewUnionNullBoolCloudEventDataDoubleString()

	r.values = append(r.values, v)
	return r.values[len(r.values)-1]
}

func (_ *MapUnionNullBoolCloudEventDataDoubleStringWrapper) AppendArray() types.Field {
	panic("Unsupported operation")
}
