// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     spec.avsc
 */
package avro

import (
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
	"io"
)

func writeMapCloudEventData(r map[string]CloudEventData, w io.Writer) error {
	err := vm.WriteLong(int64(len(r)), w)
	if err != nil || len(r) == 0 {
		return err
	}
	for k, e := range r {
		err = vm.WriteString(k, w)
		if err != nil {
			return err
		}
		err = writeCloudEventData(e, w)
		if err != nil {
			return err
		}
	}
	return vm.WriteLong(0, w)
}

type MapCloudEventDataWrapper struct {
	Target *map[string]CloudEventData
	keys   []string
	values []CloudEventData
}

func (_ *MapCloudEventDataWrapper) SetBoolean(v bool)     { panic("Unsupported operation") }
func (_ *MapCloudEventDataWrapper) SetInt(v int32)        { panic("Unsupported operation") }
func (_ *MapCloudEventDataWrapper) SetLong(v int64)       { panic("Unsupported operation") }
func (_ *MapCloudEventDataWrapper) SetFloat(v float32)    { panic("Unsupported operation") }
func (_ *MapCloudEventDataWrapper) SetDouble(v float64)   { panic("Unsupported operation") }
func (_ *MapCloudEventDataWrapper) SetBytes(v []byte)     { panic("Unsupported operation") }
func (_ *MapCloudEventDataWrapper) SetString(v string)    { panic("Unsupported operation") }
func (_ *MapCloudEventDataWrapper) SetUnionElem(v int64)  { panic("Unsupported operation") }
func (_ *MapCloudEventDataWrapper) Get(i int) types.Field { panic("Unsupported operation") }
func (_ *MapCloudEventDataWrapper) SetDefault(i int)      { panic("Unsupported operation") }

func (r *MapCloudEventDataWrapper) HintSize(s int) {
	if r.keys == nil {
		r.keys = make([]string, 0, s)
		r.values = make([]CloudEventData, 0, s)
	}
}

func (r *MapCloudEventDataWrapper) NullField(_ int) {
	panic("Unsupported operation")
}

func (r *MapCloudEventDataWrapper) Finalize() {
	for i := range r.keys {
		(*r.Target)[r.keys[i]] = r.values[i]
	}
}

func (r *MapCloudEventDataWrapper) AppendMap(key string) types.Field {
	r.keys = append(r.keys, key)
	var v CloudEventData
	v = NewCloudEventData()

	r.values = append(r.values, v)
	return &types.Record{Target: &r.values[len(r.values)-1]}
}

func (_ *MapCloudEventDataWrapper) AppendArray() types.Field { panic("Unsupported operation") }
