// Code generated by @apexlang/codegen. DO NOT EDIT.

package static

import (
	"github.com/nanobus/nanobus/pkg/transport/http/router"
)

type StaticV1Config struct {
	Paths []StaticPath `json:"paths" yaml:"paths" msgpack:"paths" mapstructure:"paths" validate:"dive"`
}

func StaticV1() (string, router.Loader) {
	return "nanobus.transport.http.static/v1", StaticV1Loader
}

type StaticPath struct {
	Path  string  `json:"path" yaml:"path" msgpack:"path" mapstructure:"path" validate:"required"`
	Dir   *string `json:"dir,omitempty" yaml:"dir,omitempty" msgpack:"dir,omitempty" mapstructure:"dir"`
	File  *string `json:"file,omitempty" yaml:"file,omitempty" msgpack:"file,omitempty" mapstructure:"file"`
	Strip *string `json:"strip,omitempty" yaml:"strip,omitempty" msgpack:"strip,omitempty" mapstructure:"strip"`
}
