include $(MAKEFILE_DIR)/common/Makefile.common
include $(MAKEFILE_DIR)/common/Makefile.common-wellknown-false
include $(MAKEFILE_DIR)/common/Makefile.common-native
include $(MAKEFILE_DIR)/common/Makefile.common-stateful
include $(MAKEFILE_DIR)/common/Makefile.common-collection
include $(MAKEFILE_DIR)/common/Makefile.common-post
include $(MAKEFILE_DIR)/common/Makefile.postlude

.PHONY: build
build: $(SOURCE_FILES)
	@cargo build --release

.PHONY: test
test: codegen
	@cargo test