include $(COMMON_DIR)/common/Makefile.common
include $(COMMON_DIR)/common/Makefile.common-wellknown-true
include $(COMMON_DIR)/common/Makefile.common-native
include $(COMMON_DIR)/common/Makefile.common-stateful
include $(COMMON_DIR)/common/Makefile.common-collection
include $(COMMON_DIR)/common/Makefile.common-post
include $(COMMON_DIR)/common/Makefile.postlude

.PHONY: build
build: $(SOURCE_FILES)
	@cargo build --release

.PHONY: test
test: codegen
	@cargo test