include $(COMMON_DIR)/common/Makefile.common
include $(COMMON_DIR)/common/Makefile.common-wellknown-false
include $(COMMON_DIR)/common/Makefile.common-native
include $(COMMON_DIR)/common/Makefile.common-ephemeral
include $(COMMON_DIR)/common/Makefile.common-collection
include $(COMMON_DIR)/common/Makefile.common-post
include $(COMMON_DIR)/common/Makefile.postlude

.PHONY: build
build: $(SOURCE_FILES)
	@cargo build

.PHONY: test
test: build ## Run tests
	cargo test
