features:
  - cargo build --features=config --no-default-features
  - cargo build --features=v1 --no-default-features
  - cargo build --features=v0 --no-default-features
  - cargo build --features=v0 --features=config --no-default-features


clean:
  rm -f docs/*
  rm -f src/v*.rs
  rm -rf json-schema/*

test:
  cargo test

v0:
  just version "v0"

version VER="v1":
  mkdir -p json-schema/{{VER}}
  apex-template definitions/{{VER}}/manifest.apex definitions/{{VER}}/templates/rust/root.hbs -p definitions/{{VER}}/templates/rust/partials > src/{{VER}}.rs
  apex-template definitions/{{VER}}/manifest.apex definitions/{{VER}}/templates/json-schema/manifest.hbs -p definitions/{{VER}}/templates/json-schema/partials > json-schema/{{VER}}/manifest.json
  prettier --write json-schema/{{VER}}/manifest.json
  just docs "{{VER}}"

docs VER="v1":
  apex-template definitions/{{VER}}/manifest.apex definitions/{{VER}}/doc-templates/rust/root.hbs -p definitions/{{VER}}/doc-templates/rust/partials > docs/{{VER}}.md;

codegen:
  mkdir -p docs
  just version v0
  just version v1
  just json-schema
  cargo +nightly fmt

json-schema:
  ts-node definitions/json-schema.ts definitions/json-schema.json.tpl json-schema/v0/manifest.json json-schema/v1/manifest.json > json-schema/manifest.json
